### PR TITLE
Assume device that matches does not match any device when executing as root, kd100 match by iProduct

### PR DESCRIPTION
**Pull request by dovideh**
Thank you for the driver. Very easy to configure and set up my different apps. 

When setting it up I wanted to test out the assume device feature.
With the current version, the device is not detected when I run it as root. The first device is also detected when not running as root (and it can be a different device as I have two Huion screens so it chooses one of them instead)

This first issue is due to a missing break statement between lines 199 and 200. 
https://github.com/mckset/KD100/blob/9436a7b11c15663a2c51e08898bbd4972ac428c8/KD100.c#L196-L204
Without it, it would go to an infinite loop as it sets the handle to NULL, which in turn is handled by the code at line 247
https://github.com/mckset/KD100/blob/9436a7b11c15663a2c51e08898bbd4972ac428c8/KD100.c#L247-L255

My C knowledge could be better, but I changed how it autodetects the device by checking the devDesc.iProduct if it is `2`. My display tablet shows `6`.  I also don't know if `libusb_get_string_descriptor_ascii` requires root privileges, as a regular user should be able to get this info by issuing `lsusb -v`.

Ideally, the detection could be handled via a configuration setting and if a substring is matched, assuming we already have a device handle and the device descriptor. That way, if Huion releases KD200 with a different iProduct, it will also cover that case.

### CODE REVIEW

**Comment by mckset** [comment]
The reason there is not a break on between lines 199 and 200 is so that the driver loops through all the devices until it finds one with the matching product information. The issue here is actually on line 200 where the driver checks the device description. For some reason, my device doesn't have a description so the driver skips all devices with a description. I assumed all other devices would be the same and I did this so that if it was used with other Huion products, the driver would most likely find the key dial before anything else. I updated this in the testing branch to instead claim the first device with a matching vendor and product id if you could try it and see if it works for you.

I'm not sure about using the device iProduct description for finding the key dial. It seems that both our devices both show the iProduct as 2, but I don't know if other devices are different or if Huion has tablets with the same iProduct. libusb_get_string_descriptor_ascii does require root permissions for some reason but by removing the check for a description length, I probably can remove it.

**Comment by dovideh** [comment]
> I updated this in the testing branch to instead claim the first device with a matching vendor and product id if you could try it and see if it works for you.

I tested the code from testing branch and found that indeed it does pick up the device. However, only if the device is the only one from Huion plugged in. Otherwise it will not correctly pick it up.



I have two screens from the vendor and they both share the same idVendor and idProduct.
In that instance, it will pick up one of the screens up first. Also they have an iProduct of 6

```
$lsusb -d 256c:006d  -vvv | grep iProduct
  iProduct                6 Huion Tablet_GS2402
  iProduct                6 Tablet Monitor
  iProduct                2 Huion Tablet_KD100
```

Hope this helps, 
Ovidiu

**Comment by mckset** [comment]
That was what I expected to happen. The '-a' flag tells the driver to assume that the first device with a matching product id is the key dial. If you run it without the flag, you will be asked to select it from a list of devices. I updated the testing branch again and to work around this. It should check the description again but this time it will accept devices without a description or with the description your device provided. If for some reason it does not take the device, it will exit the driver instead of running in a loop. If it works, I will push it to the main branch later today. Out of curiosity, did you recently get the key dial? I'm wondering if Huion recently changed the description.

**Comment by dovideh** [comment]
> If you run it without the flag, you will be asked to select it from a list of devices.I updated the testing branch again and to work around this. It should check the description again but this time it will accept devices without a description or with the description your device provided. 

Thanks, I compiled it again. It will run accordingly if executing with root permission. Executing without root permission selects the first device in the case the Kamvas display which has no keypads. As for the keypad Huion KD100 I bought in August 2021 from Amazon.


PS: I also had a H610 pro lying around which also has iProduct of 2 so my workaround does not account for that situation. :)
So thinking about this further, hardcoding the iProduct may not be ideal.
```
Bus 003 Device 006: ID 256c:006d  Huion Tablet_GS2402
Bus 003 Device 015: ID 256c:006d  Tablet Monitor
Bus 003 Device 013: ID 256c:006d HUION Huion Tablet
Bus 003 Device 012: ID 256c:006d HUION Huion Tablet_KD100
# lsusb -d 256c:006d -vvv | grep iProduct
  iProduct                6 Huion Tablet_GS2402
  iProduct                6 Tablet Monitor
  iProduct                2 Huion Tablet
  iProduct                2 Huion Tablet_KD100
```
Regarding libusb_get_string_descriptor_ascii() I got confused initially by udev after removing the rules I installed in `/etc/udev/rules.d/` for this keypad. I did not reboot the machine or check `/dev/bus` for permissions. Apparently removing the rules and calling `udevadm control --reload-rules && udevadm trigger` does not roll back the new permission which have been set , which are `0664`.
If no rules are applied and at least on Arch **all ports** will have permission 0664. 
```

# ls -l /dev/bus/usb/003
total 0
crw-rw-r-- 1 root root 189, 256 Aug 26 22:59 001
crw-rw-r-- 1 root root 189, 257 Aug 26 22:59 002
crw-rw-r-- 1 root root 189, 258 Aug 26 22:59 003
crw-rw-r-- 1 root root 189, 260 Aug 26 22:59 005
crw-rw-rw- 1 root root 189, 261 Aug 26 23:27 006
crw-rw-r-- 1 root root 189, 263 Aug 26 22:59 008
crw-rw-r-- 1 root root 189, 266 Aug 26 22:59 011
crw-rw-rw- 1 root root 189, 267 Aug 26 23:27 012
crw-rw-rw- 1 root root 189, 268 Aug 26 23:27 013
crw-rw-r-- 1 root root 189, 269 Aug 26 22:59 014
crw-rw-rw- 1 root root 189, 270 Aug 26 23:27 015
```

Having said that, I think that if a) the udev rules are in place or b) write permissions are allowed for others group (or user belongs to `plugdev` group maybe but I don't have that group here) then calling the driver with `-a` as a user should select the device using the same logic as it is used in the case when it's running as root. Without the rule (or changing the port to 0666) then the driver issues a `LIBUSB_ERROR_ACCESS` regardless if `-a` is used or not. 

Thanks again, 
Ovidiu

**Comment by mckset** [comment]
Glad to know it worked. The '-a' flag isn't necessary to run the driver and was only added to allow you to skip the device selection prompt if the key dial was the only Huion product you had connected (as it is in my case). Seeing how Huion devices share the same product and vendor ids, it doesn't surprise me that another one of their products had the same iProduct number. Thank you for verifying that though. Like I said, the only Huion product I have is the mini key dial so I couldn't test it myself. 

I changed the suggested udev rule in the readme and removed the 'plugdev' group so it should work without needing to make or adding yourself to a plugdev group. I realize I should have mentioned that it wasn't necessary. I'll finish testing the driver tomorrow and merge it with the main branch. Thank you.

**Pull request closed without merging**
